"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SelectMagic } from "@/components/ui/select-magic";
import { useTranslations } from "@/lib/language-context";
import { ArrowLeft, Save, Package } from "lucide-react";
import Link from "next/link";

interface NewProductFormData {
  name: string;
  category: string;
  unit: string;
  priceSell: string;
  priceCost: string;
  qtyOnHand: string;
  minQty: string;
  isRawMaterial: boolean;
  isFinishedGood: boolean;
}

export default function NewProductPage() {
  const router = useRouter();
  const t = useTranslations("inventory");
  const common = useTranslations("common");

  const [formData, setFormData] = useState<NewProductFormData>({
    name: "",
    category: "",
    unit: "pcs",
    priceSell: "",
    priceCost: "",
    qtyOnHand: "0",
    minQty: "",
    isRawMaterial: false,
    isFinishedGood: true,
  });

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleInputChange =
    (field: keyof NewProductFormData) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
      const value =
        e.target.type === "checkbox" ? (e.target as HTMLInputElement).checked : e.target.value;
      setFormData((prev) => ({
        ...prev,
        [field]: value,
      }));
    };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Basic validation - only name is required, prices can be 0
    if (!formData.name) {
      setError("Please fill in the product name");
      return;
    }

    try {
      setLoading(true);
      setError(null);

      const response = await fetch("/api/inventory", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to create product");
      }

      const result = await response.json();
      router.push(`/inventory/${result.product.id}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
      console.error("Error creating product:", err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex-1 space-y-4 p-8 pt-6">
      {/* Header */}
      <div className="flex items-center space-x-4">
        <Link href="/inventory">
          <Button className="h-8 w-8 p-0">
            <ArrowLeft className="h-4 w-4" />
          </Button>
        </Link>
        <div>
          <h2 className="text-3xl font-bold tracking-tight">
            {t("addProduct")}
          </h2>
          <p className="text-muted-foreground">
            Create a new product in your inventory
          </p>
        </div>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="max-w-2xl">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <Package className="mr-2 h-4 w-4" />
              {t("addProductTitle")}
            </CardTitle>
            <CardDescription>
              {t("addProductDescription")}
              <br />
              <span className="text-sm text-green-600 font-medium">
                {t("skuAutoGenerated")}
              </span>
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {error && (
              <div className="p-4 text-red-600 bg-red-50 border border-red-200 rounded">
                {error}
              </div>
            )}

            {/* Basic Information */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="name">{t("productName")} *</Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={handleInputChange("name")}
                  placeholder={t("placeholderProductName")}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="category">{t("category")}</Label>
                <SelectMagic 
                  value={formData.category} 
                  onChange={handleInputChange("category")}
                >
                  <option value="">{t("selectCategory")}</option>
                  <option value="raw-material">{t("rawMaterial")}</option>
                  <option value="finished-good">{t("finishedGood")}</option>
                  <option value="semi-finished">{t("semiFinished")}</option>
                  <option value="consumable">{t("consumable")}</option>
                  <option value="packaging">{t("packaging")}</option>
                  <option value="maintenance">{t("maintenance")}</option>
                </SelectMagic>
              </div>
              <div className="space-y-2">
                <Label htmlFor="unit">{t("unit")}</Label>
                <Input
                  id="unit"
                  value={formData.unit}
                  onChange={handleInputChange("unit")}
                  placeholder={t("placeholderUnitExamples")}
                />
              </div>
            </div>

            {/* Pricing */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="priceSell">{t("priceSell")}</Label>
                <Input
                  id="priceSell"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.priceSell}
                  onChange={handleInputChange("priceSell")}
                  placeholder="0.00"
                />
                <p className="text-xs text-muted-foreground">
                  {t("priceCanBeZero")}
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="priceCost">{t("priceCost")}</Label>
                <Input
                  id="priceCost"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.priceCost}
                  onChange={handleInputChange("priceCost")}
                  placeholder="0.00"
                />
                <p className="text-xs text-muted-foreground">
                  {t("priceCanBeZero")}
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="qtyOnHand">{t("qtyOnHand")}</Label>
                <Input
                  id="qtyOnHand"
                  type="number"
                  value={formData.qtyOnHand}
                  onChange={handleInputChange("qtyOnHand")}
                  placeholder={t("placeholderQtyOnHand")}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="minQty">{t("minQty")}</Label>
                <Input
                  id="minQty"
                  type="number"
                  value={formData.minQty}
                  onChange={handleInputChange("minQty")}
                  placeholder={t("placeholderMinQty")}
                />
              </div>
            </div>

            {/* Product Type */}
            <div className="space-y-2">
              <Label>{t("productType")}</Label>
              <div className="flex items-center gap-4">
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={formData.isRawMaterial}
                    onChange={handleInputChange("isRawMaterial")}
                  />
                  {t("rawMaterial")}
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={formData.isFinishedGood}
                    onChange={handleInputChange("isFinishedGood")}
                  />
                  {t("finishedGood")}
                </label>
              </div>
            </div>

            {/* Actions */}
            <div className="flex justify-end gap-2 mt-6">
              <Button type="submit" disabled={loading}>
                {loading ? common("saving") : common("save")}
              </Button>
              <Link href="/inventory">
                <Button type="button" variant="outline">
                  {common("cancel")}
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </form>
    </div>
  );
}
